version: "3.8"

services:
  vocalia-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

# To run the app, use the following command in terminal: docker-compose up --build
